#!/usr/bin/env python3
"""Regenerate the optimize/sweep score table in SCORES.md from run artifacts.

Scans ``runs/<skill>/<timestamp>/cost.json`` and rewrites only the block
between the AUTO markers in ``SCORES.md``. The manual "Eval log" section and
everything else are left untouched. Stdlib only — no venv needed.

Run from this directory:  python3 scores.py
"""
from __future__ import annotations
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
RUNS = HERE / "runs"
LEDGER = HERE / "SCORES.md"
START = "<!-- AUTO:start"
END = "<!-- AUTO:end -->"


def _rows() -> list[tuple]:
    rows = []
    for cj in RUNS.glob("*/*/cost.json"):
        ts = cj.parent.name                       # YYYYMMDD-HHMMSS
        date = f"{ts[0:4]}-{ts[4:6]}-{ts[6:8]}" if len(ts) >= 8 else ts
        try:
            d = json.loads(cj.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        inc, best = d.get("incumbent_val_mean"), d.get("best_val_mean")
        delta = best - inc if _num(best) and _num(inc) else None
        rows.append((ts, date, cj.parent.parent.name, inc, best,
                     d.get("best_test_mean"), d.get("accepted_epochs"),
                     d.get("spent_usd"), delta))
    rows.sort()                                   # chronological by timestamp
    return rows


def _num(x) -> bool:
    return isinstance(x, (int, float))


def _f(x, n: int = 3) -> str:
    return f"{x:.{n}f}" if _num(x) else "—"


def _delta(x) -> str:
    if not _num(x):
        return "—"
    return f"+{x:.3f}" if x >= 0 else f"{x:.3f}"


def _table() -> str:
    head = ("| Date | Skill | Incumbent val | Best val | Δ val | Best test "
            "| Accepted epochs | Cost |\n"
            "|---|---|---|---|---|---|---|---|")
    out = [head]
    for ts, date, skill, inc, best, test, ae, cost, delta in _rows():
        cost_s = f"${cost:.2f}" if _num(cost) else "—"
        ae_s = str(ae) if ae is not None else "—"
        out.append(f"| {date} | {skill} | {_f(inc)} | {_f(best)} | {_delta(delta)} "
                   f"| {_f(test)} | {ae_s} | {cost_s} |")
    return "\n".join(out)


def main() -> None:
    text = LEDGER.read_text()
    pre, sep, rest = text.partition(START)
    if not sep:
        raise SystemExit(f"{LEDGER.name}: missing '{START}' marker")
    _, sep2, post = rest.partition(END)
    if not sep2:
        raise SystemExit(f"{LEDGER.name}: missing '{END}' marker")
    block = (f"{START} — generated by scores.py; do not edit between these "
             f"markers -->\n\n{_table()}\n\n{END}")
    LEDGER.write_text(pre + block + post)
    print(f"Updated {LEDGER.name} with {len(_rows())} runs.")


if __name__ == "__main__":
    main()
